server:
  port: 8080

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

app:
  rabbit:
    exchange: pedidos.exchange.seu-nome
    dlx: pedidos.dlx.seu-nome
    queue-entrada: pedidos.entrada.seu-nome
    queue-dlq: pedidos.entrada.seu-nome.dlq
    queue-status-sucesso: pedidos.status.sucesso.seu-nome
    queue-status-falha: pedidos.status.falha.seu-nome
    routing-entrada: pedidos.entrada
    routing-status-sucesso: pedidos.status.sucesso
    routing-status-falha: pedidos.status.falha